development:
  database: gem_camp
  username: root
  password: qwer4321
  adapter: mysql2
  encoding: utf8mb4
  host: db
test:
  database: gem_camp_test
  username: root
  password: qwer4321
  adapter: mysql2
  encoding: utf8mb4
  host: db